SELECT X2_CHAVE,X2_NOME FROM SX2990 
WHERE X2_CHAVE IN( 'FN6','FN7','FN6','FN7','FN9','FNG','FNH','FNR','FNS','SN0','SN1','SN3','SN4','SN5','SNC','SNG','SNL' ) 
--( X2_CHAVE LIKE 'FN%' OR X2_CHAVE LIKE 'SN%' )
ORDER BY X2_CHAVE

-- VERIFICA DAS TABELAS EXISTENTES QUAIS TEM REGISTRO
SELECT 'SELECT ''' + X2_CHAVE + ''', COUNT(*),'''' FROM ' + X2_CHAVE + '010 UNION ALL' 
FROM SX2990 
WHERE ( X2_CHAVE LIKE 'FN%' 
OR X2_CHAVE LIKE 'SN%' ) AND
X2_CHAVE NOT IN( 'FN1','FN2','FN3','FN4','FN5','FNK', 'FNL','FNO','FNP','FNV','FNW','FNX','FNY',
'SNI','SNJ','SNM', 'SNT'  )
ORDER BY X2_CHAVE

-- VERIFICA AS TABELAS EXISTENTES
SELECT 'SELECT ''' + X2_CHAVE + '010'', COUNT(*),'''' FROM SYS.OBJECTS WHERE NAME = '''+ X2_CHAVE +'010'' UNION ALL' 
FROM SX2990 
WHERE ( X2_CHAVE LIKE 'FN%' 
OR X2_CHAVE LIKE 'SN%' )
ORDER BY X2_CHAVE


